version: '3'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:



