version: '3'

services:
  api:
    build: .
    container_name: api
    entrypoint: dockerize -wait tcp://mongo:27017 ./.docker/entrypoint.sh
    environment:
      - TICKET_API_URL=https://api.ticket.com.br/mobile/usuarios/v3
      - MONGO_URL=mongodb://mongo:27017/ticket-scraper
      - APP_SECRET=35fc3f38be4eb737942a65ab36c166fd
      - PORT=8080
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:



